// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnIbB0dODp51VZLieJGZmJ-Wwdy5N7mcY',
    appId: '1:751631328296:web:a830e2366946fe94be811d',
    messagingSenderId: '751631328296',
    projectId: 'puzzle-game-cb8ff',
    authDomain: 'puzzle-game-cb8ff.firebaseapp.com',
    databaseURL: 'https://puzzle-game-cb8ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'puzzle-game-cb8ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBWB5W0yEmk2ATSmTTRbDT0W6Bw9HLwsk',
    appId: '1:751631328296:android:99a8581d6ad8fc7bbe811d',
    messagingSenderId: '751631328296',
    projectId: 'puzzle-game-cb8ff',
    databaseURL: 'https://puzzle-game-cb8ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'puzzle-game-cb8ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8W-vkmOLrY1oCi2cJPh1-l10WGVUhRbo',
    appId: '1:751631328296:ios:8ff0abd678e3ea66be811d',
    messagingSenderId: '751631328296',
    projectId: 'puzzle-game-cb8ff',
    databaseURL: 'https://puzzle-game-cb8ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'puzzle-game-cb8ff.appspot.com',
    iosBundleId: 'com.example.gameFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8W-vkmOLrY1oCi2cJPh1-l10WGVUhRbo',
    appId: '1:751631328296:ios:bf841022a97a943abe811d',
    messagingSenderId: '751631328296',
    projectId: 'puzzle-game-cb8ff',
    databaseURL: 'https://puzzle-game-cb8ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'puzzle-game-cb8ff.appspot.com',
    iosBundleId: 'com.example.gameFlutter.RunnerTests',
  );
}
